### ISSUE TITLE
hintsFileName in config.ini doesn't work

### ISSUE THREAD

**Issue by glennklockwood** [IO500/io500#22]
My config.ini contained this configuration:

```
[ior-hard]
API = mpiio
hintsFileName = ./hints.gerty
```

which resulted in a runtime error of

```
Error invalid argument: -U
Error invalid argument: ./hints.gerty
Error invalid argument: mpiio
Invalid options
Synopsis ./ior
```

Looks like IOR dropped the `-U` flag when it was turned into a module-specific parameter, but IO500 wasn't updated accordingly.

**Comment by JulianKunkel** [comment]
Thanks for reporting this. In the VI4IO testing branch (see PR) is now a patch. 
It was indeed replaced with --mpiio.hintsFileName
So the correct config would be:
API = mpiio --mpiio.hintsFileName=./hints.gerty
