### ISSUE TITLE
compile-time error with INI_UNSET_FLOAT

### ISSUE THREAD

**Issue by Michael-Hennecke** [IO500/io500#26]
With the Intel compiler (2020.4.304), the following causes a compile-time error (occurred during io500-isc21_v1 prepare):

```
$ ./prepare.sh
...
src/ini-parse.c(285): error #264: floating-point value does not fit in required floating-point type
              *(float*) o->var = INI_UNSET_FLOAT;
                                 ^
 compilation aborted for src/ini-parse.c (code 2)
make: *** [build/ini-parse.o] Error 2

```  

The culprit seems to be this #define:
 
`include/io500-util.h:#define INI_UNSET_FLOAT 1e307
`

**Comment by JulianKunkel** [comment]
Thanks, that is helpful, I hope with the proper limit of 1e38, it works.

**Comment by Michael-Hennecke** [comment]
yes, i can confirm that it compiles cleanly with 1e38...
