### ISSUE TITLE
Any options to allow "ior-hard-read" and "ior-hard-write" read/write separate files ("-F" for ior)?

### ISSUE THREAD

**Issue by wiliamhuang** [IO500/io500#32]
Currently, "ior-hard-read" and "ior-hard-write" only supports reading/writing a single file for all processes. Is it allowed to turn on "-F" option? Thank you! 

-lei

**Comment by JulianKunkel** [comment]
Hi, unfortunately, -F is not allowed for IOR hard!

**Comment by adilger** [comment]
@wiliamhuang - an important factor for the "hard" part of "ior-hard" is that they are writing/reading from a single file for all processes.  The other "hard' part is that the write/read operations are not aligned to a page/block boundary

**Comment by wiliamhuang** [comment]
Understand. Thank you very much for your clarification!
