### ISSUE TITLE
Verify score hash does not match generated one

### ISSUE THREAD

**Issue by mchaarawi** [IO500/io500#33]
When running the verify phase over the generated results.txt file, I found that the score hash is always failing with the isc21 tag.
After some digging I found the issue to be that the hash generation in the verifier program adds more items to calculate the hash vs what the original program does to compute the hash when the benchmark is run.
Specifically those three items are added by the verifier but were not used when computing the score hash in the benchmark:
timestamp score
BW score
MD score

**Comment by JulianKunkel** [comment]
Thanks for reporting. Your analysis is correct. The PR will resolve this issue.

**Comment by johannlombardi** [comment]
Thanks @JulianKunkel. Could you please advise whether we shall we apply it for ISC21 submissions or stick to the original tag?

**Comment by mchaarawi** [comment]
Confirmed the PR does resolve the issue.
Same question as Johann as what the committee is going to require for isc21..

**Comment by adilger** [comment]
Patch included in io500-isc21_v2 tag.
